version: "3"
services:

  oj-redis:
    image: redis:4.0-alpine
    container_name: oj-redis
    restart: always
    volumes:
      - ./data/redis:/data

  oj-postgres:
    image: postgres:10-alpine
    container_name: oj-postgres
    restart: always
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=skojda
      - POSTGRES_USER=skoj
      - POSTGRES_PASSWORD=Nice_try

  judge-server:
    image: registry.cn-heyuan.aliyuncs.com/nice_try_sk/judge-server:v1.1
    container_name: judge-server
    restart: always
    read_only: true
    cap_drop:
      - SETPCAP
      - MKNOD
      - NET_BIND_SERVICE
      - SYS_CHROOT
      - SETFCAP
      - FSETID
    tmpfs:
      - /tmp
    volumes:
      - ./data/backend/test_case:/test_case:ro
      - ./data/judge_server/log:/log
      - ./data/judge_server/run:/judger
    environment:
      - SERVICE_URL=http://judge-server:8080
      - BACKEND_URL=http://oj-backend:8000/api/judge_server_heartbeat/
      - TOKEN=4de14b1345f5ccc9c4522235006e1631

  oj-backend:
    image: registry.cn-heyuan.aliyuncs.com/nice_try_sk/skoj_backend:v1.3
    container_name: oj-backend
    restart: always
    depends_on:
      - oj-redis
      - oj-postgres
      - judge-server
    volumes:
      - ./data/backend:/data
      # - ./data/backend/dist:/app/dist #前端打包挂载
    environment:
      - POSTGRES_DB=skojda
      - POSTGRES_USER=skoj
      - POSTGRES_PASSWORD=Nice_try
      - JUDGE_SERVER_TOKEN=4de14b1345f5ccc9c4522235006e1631
      # - FORCE_HTTPS=1
      # - STATIC_CDN_HOST=cdn.oj.com
    ports:
      - "0.0.0.0:8000:8000" #后端端口
      - "0.0.0.0:80:8000" #前端http端口
      - "0.0.0.0:443:1443" #前端https端口
